"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

const STRUCTURE_PATH_PREFIX = "/academic-director/intakes";

async function requireAcademicDirectorUser() {
  const session = await auth();

  if (!session?.user?.id) {
    redirect("/login");
  }

  const user = await prisma.user.findUnique({
    where: {
      id: session.user.id,
    },
    select: {
      id: true,
      isActive: true,
      accountStatus: true,
      role: {
        select: {
          name: true,
        },
      },
    },
  });

  if (!user || !user.isActive || user.accountStatus !== "ACTIVE") {
    redirect("/unauthorized");
  }

  const roleName = user.role.name;

  if (roleName !== "academic_director" && roleName !== "super_admin") {
    redirect("/unauthorized");
  }

  return user;
}

function getString(formData: FormData, key: string) {
  const value = formData.get(key);

  if (typeof value !== "string" || !value.trim()) {
    throw new Error(`Missing ${key}`);
  }

  return value.trim();
}

function getInt(formData: FormData, key: string) {
  const value = Number(getString(formData, key));

  if (!Number.isInteger(value) || value < 1) {
    throw new Error(`Invalid ${key}`);
  }

  return value;
}

function redirectBack(intakeId: string, type: "success" | "error", message: string) {
  redirect(
    `${STRUCTURE_PATH_PREFIX}/${intakeId}/structure?${type}=${encodeURIComponent(message)}`,
  );
}

async function getIntakeOrRedirect(intakeId: string) {
  const intake = await prisma.intake.findUnique({
    where: {
      id: intakeId,
    },
    select: {
      id: true,
      courseId: true,
    },
  });

  if (!intake) {
    redirect("/academic-director/intakes");
  }

  return intake;
}

export async function generateStandardAcademicStructure(formData: FormData) {
  const user = await requireAcademicDirectorUser();
  const intakeId = getString(formData, "intakeId");
  const yearsCount = getInt(formData, "yearsCount");
  const semestersPerYear = getInt(formData, "semestersPerYear");

  if (yearsCount > 6 || semestersPerYear > 4) {
    redirectBack(intakeId, "error", "Use a smaller academic structure.");
  }

  const intake = await getIntakeOrRedirect(intakeId);

  await prisma.$transaction(async (tx) => {
    for (let yearNumber = 1; yearNumber <= yearsCount; yearNumber += 1) {
      const yearTitle = `Year ${yearNumber}`;

      let courseYear = await tx.courseYear.findFirst({
        where: {
          courseId: intake.courseId,
          yearNumber,
        },
        select: {
          id: true,
        },
      });

      if (!courseYear) {
        courseYear = await tx.courseYear.create({
          data: {
            courseId: intake.courseId,
            yearNumber,
            title: yearTitle,
            sequence: yearNumber,
            isActive: true,
          },
          select: {
            id: true,
          },
        });
      } else {
        await tx.courseYear.update({
          where: {
            id: courseYear.id,
          },
          data: {
            title: yearTitle,
            sequence: yearNumber,
            isActive: true,
          },
        });
      }

      for (let semesterNumber = 1; semesterNumber <= semestersPerYear; semesterNumber += 1) {
        const existingSemester = await tx.courseSemester.findFirst({
          where: {
            courseYearId: courseYear.id,
            sequence: semesterNumber,
          },
          select: {
            id: true,
          },
        });

        const title = `Semester ${semesterNumber}`;

        if (!existingSemester) {
          await tx.courseSemester.create({
            data: {
              courseYearId: courseYear.id,
              title,
              semesterNumber,
              sequence: semesterNumber,
              periodType: "SEMESTER",
              isActive: true,
            },
          });
        } else {
          await tx.courseSemester.update({
            where: {
              id: existingSemester.id,
            },
            data: {
              title,
              semesterNumber,
              sequence: semesterNumber,
              periodType: "SEMESTER",
              isActive: true,
            },
          });
        }
      }
    }
  });

  revalidatePath(`${STRUCTURE_PATH_PREFIX}/${intakeId}`);
  revalidatePath(`${STRUCTURE_PATH_PREFIX}/${intakeId}/structure`);
  revalidatePath("/coordinator/course-units");

  redirectBack(
    intakeId,
    "success",
    `Academic structure generated by ${user.role.name.replaceAll("_", " ")}.`,
  );
}

export async function createAcademicYear(formData: FormData) {
  await requireAcademicDirectorUser();

  const intakeId = getString(formData, "intakeId");
  const yearNumber = getInt(formData, "yearNumber");
  const sequence = getInt(formData, "sequence");
  const title = getString(formData, "title");

  const intake = await getIntakeOrRedirect(intakeId);

  const existingYear = await prisma.courseYear.findFirst({
    where: {
      courseId: intake.courseId,
      OR: [{ yearNumber }, { sequence }],
    },
    select: {
      id: true,
    },
  });

  if (existingYear) {
    redirectBack(intakeId, "error", "That year number or sequence already exists.");
  }

  await prisma.courseYear.create({
    data: {
      courseId: intake.courseId,
      yearNumber,
      title,
      sequence,
      isActive: true,
    },
  });

  revalidatePath(`${STRUCTURE_PATH_PREFIX}/${intakeId}`);
  revalidatePath(`${STRUCTURE_PATH_PREFIX}/${intakeId}/structure`);
  revalidatePath("/coordinator/course-units");

  redirectBack(intakeId, "success", "Academic year created.");
}

export async function createAcademicSemester(formData: FormData) {
  await requireAcademicDirectorUser();

  const intakeId = getString(formData, "intakeId");
  const courseYearId = getString(formData, "courseYearId");
  const title = getString(formData, "title");
  const sequence = getInt(formData, "sequence");

  const rawSemesterNumber = formData.get("semesterNumber");
  const semesterNumber =
    typeof rawSemesterNumber === "string" && rawSemesterNumber.trim()
      ? Number(rawSemesterNumber)
      : null;

  const rawPeriodType = getString(formData, "periodType");
  const periodType = rawPeriodType === "TRAINING_BLOCK" ? "TRAINING_BLOCK" : "SEMESTER";

  const intake = await getIntakeOrRedirect(intakeId);

  const courseYear = await prisma.courseYear.findFirst({
    where: {
      id: courseYearId,
      courseId: intake.courseId,
    },
    select: {
      id: true,
    },
  });

  if (!courseYear) {
    redirectBack(intakeId, "error", "Academic year does not belong to this intake course.");
  }

  const existingSemester = await prisma.courseSemester.findFirst({
    where: {
      courseYearId,
      sequence,
    },
    select: {
      id: true,
    },
  });

  if (existingSemester) {
    redirectBack(intakeId, "error", "A semester with that sequence already exists in this year.");
  }

  await prisma.courseSemester.create({
    data: {
      courseYearId,
      title,
      semesterNumber: semesterNumber && Number.isInteger(semesterNumber) ? semesterNumber : null,
      sequence,
      periodType,
      isActive: true,
    },
  });

  revalidatePath(`${STRUCTURE_PATH_PREFIX}/${intakeId}`);
  revalidatePath(`${STRUCTURE_PATH_PREFIX}/${intakeId}/structure`);
  revalidatePath("/coordinator/course-units");

  redirectBack(intakeId, "success", "Semester created.");
}

export async function deactivateAcademicSemester(formData: FormData) {
  await requireAcademicDirectorUser();

  const intakeId = getString(formData, "intakeId");
  const semesterId = getString(formData, "semesterId");

  const intake = await getIntakeOrRedirect(intakeId);

  const semester = await prisma.courseSemester.findFirst({
    where: {
      id: semesterId,
      courseYear: {
        courseId: intake.courseId,
      },
    },
    select: {
      id: true,
    },
  });

  if (!semester) {
    redirectBack(intakeId, "error", "Semester not found for this course.");
  }

  const existingAssignments = await prisma.semesterUnitAssignment.count({
    where: {
      semesterId,
    } as any,
  });

  if (existingAssignments > 0) {
    redirectBack(
      intakeId,
      "error",
      "This semester already has unit assignments. Keep it active to preserve records.",
    );
  }

  await prisma.courseSemester.update({
    where: {
      id: semesterId,
    },
    data: {
      isActive: false,
    },
  });

  revalidatePath(`${STRUCTURE_PATH_PREFIX}/${intakeId}`);
  revalidatePath(`${STRUCTURE_PATH_PREFIX}/${intakeId}/structure`);
  revalidatePath("/coordinator/course-units");

  redirectBack(intakeId, "success", "Semester deactivated.");
}

export async function deactivateAcademicYear(formData: FormData) {
  await requireAcademicDirectorUser();

  const intakeId = getString(formData, "intakeId");
  const courseYearId = getString(formData, "courseYearId");

  const intake = await getIntakeOrRedirect(intakeId);

  const courseYear = await prisma.courseYear.findFirst({
    where: {
      id: courseYearId,
      courseId: intake.courseId,
    },
    select: {
      id: true,
    },
  });

  if (!courseYear) {
    redirectBack(intakeId, "error", "Academic year not found for this course.");
  }

  const existingAssignments = await prisma.semesterUnitAssignment.count({
    where: {
      semester: {
        courseYearId,
      },
    } as any,
  });

  if (existingAssignments > 0) {
    redirectBack(
      intakeId,
      "error",
      "This year already has unit assignments. Keep it active to preserve records.",
    );
  }

  await prisma.$transaction([
    prisma.courseSemester.updateMany({
      where: {
        courseYearId,
      },
      data: {
        isActive: false,
      },
    }),
    prisma.courseYear.update({
      where: {
        id: courseYearId,
      },
      data: {
        isActive: false,
      },
    }),
  ]);

  revalidatePath(`${STRUCTURE_PATH_PREFIX}/${intakeId}`);
  revalidatePath(`${STRUCTURE_PATH_PREFIX}/${intakeId}/structure`);
  revalidatePath("/coordinator/course-units");

  redirectBack(intakeId, "success", "Academic year deactivated.");
}

function getOptionalString(formData: FormData, key: string) {
  const value = formData.get(key);

  if (typeof value !== "string") {
    return "";
  }

  return value.trim();
}

export async function approveCoordinatorUnitPlan(formData: FormData) {
  const user = await requireAcademicDirectorUser();
  const intakeId = getString(formData, "intakeId");
  const reviewNote = getOptionalString(formData, "reviewNote") || "Approved by Academic Director.";

  await getIntakeOrRedirect(intakeId);

  const submittedCount = await prisma.semesterUnitAssignment.count({
    where: {
      intakeId,
      status: "SUBMITTED",
    } as any,
  });

  if (submittedCount === 0) {
    redirectBack(intakeId, "error", "There is no submitted coordinator plan to approve.");
  }

  await prisma.semesterUnitAssignment.updateMany({
    where: {
      intakeId,
      status: "SUBMITTED",
    } as any,
    data: {
      status: "APPROVED",
      reviewedById: user.id,
      reviewedAt: new Date(),
      reviewNote,
      rejectionReason: null,
    } as any,
  });

  revalidatePath(`${STRUCTURE_PATH_PREFIX}/${intakeId}`);
  revalidatePath(`${STRUCTURE_PATH_PREFIX}/${intakeId}/structure`);
  revalidatePath("/coordinator/course-units");

  redirectBack(intakeId, "success", "Coordinator unit plan approved. Lecturer allocation can now be opened.");
}

export async function requestCoordinatorUnitPlanAmendment(formData: FormData) {
  const user = await requireAcademicDirectorUser();
  const intakeId = getString(formData, "intakeId");
  const reviewNote = getString(formData, "reviewNote");

  await getIntakeOrRedirect(intakeId);

  const submittedCount = await prisma.semesterUnitAssignment.count({
    where: {
      intakeId,
      status: "SUBMITTED",
    } as any,
  });

  if (submittedCount === 0) {
    redirectBack(intakeId, "error", "There is no submitted coordinator plan to return for amendment.");
  }

  await prisma.semesterUnitAssignment.updateMany({
    where: {
      intakeId,
      status: "SUBMITTED",
    } as any,
    data: {
      status: "AMENDMENT_REQUESTED",
      reviewedById: user.id,
      reviewedAt: new Date(),
      reviewNote,
      rejectionReason: reviewNote,
    } as any,
  });

  revalidatePath(`${STRUCTURE_PATH_PREFIX}/${intakeId}`);
  revalidatePath(`${STRUCTURE_PATH_PREFIX}/${intakeId}/structure`);
  revalidatePath("/coordinator/course-units");

  redirectBack(intakeId, "success", "Coordinator unit plan returned for amendment.");
}

